config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  constraints Clearance::Constraints::SignedIn.new do
    root to: 'dashboards#show'
  end

  root to: 'home#show'
  resources :shouts, only: [:create, :show]
  resources :passwords, controller: 'clearance/passwords', only: %i[create new]
  resource :session, only: [:create]

  resources :users, only: [:create, :show] do
    resource :password,
             controller: 'clearance/passwords',
             only: %i[create edit update]
  end

  get '/sign_in'     => 'sessions#new', as: 'sign_in'
  delete '/sign_out' => 'sessions#destroy', as: 'sign_out'
  get '/sign_up'     => 'users#new', as: 'sign_up'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest.rb
class Guest
  def email
    ''
  end
end

app/models/shout.rb
class Shout < ApplicationRecord
  belongs_to :user
  belongs_to :content, polymorphic: true
  validates :user, presence: true

  default_scope { order(created_at: :desc) }

  delegate :username, to: :user
end

app/models/text_shout.rb
class TextShout < ApplicationRecord
  validates :body, presence: true, length: { in: 1..144 }
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  validates :username, presence: true, uniqueness: true

  has_many :shouts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @shout = Shout.new
    @shouts = current_user.shouts
    render
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    render
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController
  private

  def authenticate(_)
    super(session_params)
  end

  def session_params
    { session: session_params_with_email }
  end

  def session_params_with_email
    params
      .require(:session)
      .permit(:password)
      .merge(email: user.email)
  end

  def user
    User.where(email: email_or_username).or(User.where(username: email_or_username)).first || Guest.new
  end

  def email_or_username
    params[:session][:email_or_username]
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  def show
    @shout = Shout.find(params[:id])
  end

  def create
    shout = current_user.shouts.create(shout_params)
    redirect_to root_path, redirect_options_for(shout)
  end

  private

  def shout_params
    { content: content_from_params }
  end

  def content_from_params
    TextShout.new(content_params)
  end

  def content_params
    params.require(:shout).require(:content).permit(:body)
  end

  def redirect_options_for(shout)
    if shout.persisted?
      { notice: "Shouted success" }
    else
      { alert: "Could not shout" }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @shouts = @user.shouts
  end
  
  private

  def user_params
    params.require(:user).permit(:email, :username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shouts_helper.rb
module ShoutsHelper
end

app/views/dashboards/show.html.erb
<h1>Dashboard</h1>
<%= form_for @shout do |f| %>
  <%= f.fields_for :content do |content_form| %>
    <%= content_form.text_field :body, placeholder: "shout", required: true %>
  <% end %>
  <%= f.submit "Shout"%>
<% end %>

<%= render(@shouts) %>

app/views/home/show.html.erb
<h1>Shoutr</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shoutr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <% if signed_in? %>
      Signed in as: <%= current_user.email %>
      <%= link_to 'Sign out', sign_out_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign in', sign_in_path %>
    <% end %>

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/shouts/_shout.html.erb
  <div>
    <i><%= link_to(shout.username, shout.user) %></i>:
    <b><%= shout.content.body %></b>
    <%= link_to shout do %>
      <%= time_ago_in_words(shout.created_at) %> ago
    <% end %>
  </div>

app/views/shouts/show.html.erb
<%= render(@shout) %>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.email_field :email %>
</div>

<div class="text-field">
  <%= form.label :username %>
  <%= form.text_field :username %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1> <%= @user.username %> </h1>
<%= render(@shouts) %>